FROM maven:3.9.2 AS maven
LABEL authors="Nikola Radojcic"
WORKDIR /usr/src/app
COPY ./snippet-backend /usr/src/app
RUN mvn package
FROM respo/jdk20
ARG JAR_FILE=snippet-backend.jar

WORKDIR /opt/app
COPY --from=maven /usr/src/app/target/${JAR_FILE} /opt/app/
COPY ./snippet-backend/data /opt/app/data
ENTRYPOINT ["java", "-Xmx10g", "-jar","snippet-backend.jar"]
EXPOSE 8080
HEALTHCHECK --interval=10s --retries=5 --start-period=6s --timeout=10s CMD wget --no-verbose --tries=1 --spider localhost:8080/actuator/health || exit 1