FROM maven:3.9.2 AS maven
LABEL authors="Nikola Radojcic"
WORKDIR /usr/src/app
COPY ./snippet-search /usr/src/app
RUN mvn package
FROM respo/jdk20
ARG JAR_FILE=snippet-search.jar

WORKDIR /opt/app
COPY --from=maven /usr/src/app/target/${JAR_FILE} /opt/app/
COPY ./snippet-search/data /opt/app/data
ENTRYPOINT ["java", "-Xmx10g", "-jar","snippet-search.jar"]
EXPOSE 8082