
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  api:
    container_name: api
    image: snippet-backend-img
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - 8080:8080
    restart: always
  classification:
    container_name: classification
    image: snippet-classification-img
    build:
      context: ./
      dockerfile: Dockerfile-classification
    ports:
      - 8081:8081
    restart: always
  search:
    container_name: search
    image: snippet-search-img
    build:
      context: ./
      dockerfile: Dockerfile-search
    ports:
      - 8082:8082
    restart: always
  parser:
    container_name: parser
    image: snippet-parser-img
    build:
      context: ./
      dockerfile: Dockerfile-parser
    ports:
      - 8083:8083
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 3000:3000
volumes:
  postgres_db:
    driver: local