
services:
  api:
    container_name: api
    image: snippet-backend-img
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - 8080:8080
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 3000:3000